// <auto-generated />
using System;
using Menchul.GeoNames.org.MSSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Menchul.GeoNames.org.MSSQL.Migrations
{
    [DbContext(typeof(GeoNamesOrgMSSQLDbContext))]
    partial class GeoNamesOrgMSSQLDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Menchul.GeoNames.org.Models.AlternateNameV2", b =>
                {
                    b.Property<long>("GeoNameId")
                        .HasColumnType("bigint");

                    b.Property<string>("C4")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .IsFixedLength(false);

                    b.Property<string>("C5")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .IsFixedLength(false);

                    b.Property<string>("C6")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .IsFixedLength(false);

                    b.Property<string>("C7")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .IsFixedLength(false);

                    b.Property<string>("C8")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .IsFixedLength(false);

                    b.Property<string>("C9")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .IsFixedLength(false);

                    b.Property<long>("GeoNameIdRef")
                        .HasColumnType("bigint");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .IsFixedLength(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .IsFixedLength(false);

                    b.HasKey("GeoNameId")
                        .HasName("PK_AlternateNamesV2");

                    b.HasIndex("GeoNameIdRef");

                    b.ToTable("AlternateNamesV2", "gno");
                });

            modelBuilder.Entity("Menchul.GeoNames.org.Models.Continent", b =>
                {
                    b.Property<long>("GeoNameId")
                        .HasColumnType("bigint");

                    b.Property<string>("ISO2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .IsFixedLength(false);

                    b.HasKey("GeoNameId")
                        .HasName("PK_Continents");

                    b.ToTable("Continents", "gno");

                    b.HasData(
                        new
                        {
                            GeoNameId = 6255146L,
                            ISO2 = "AF",
                            Name = "Africa"
                        },
                        new
                        {
                            GeoNameId = 6255147L,
                            ISO2 = "AS",
                            Name = "Asia"
                        },
                        new
                        {
                            GeoNameId = 6255148L,
                            ISO2 = "EU",
                            Name = "Europe"
                        },
                        new
                        {
                            GeoNameId = 6255149L,
                            ISO2 = "NA",
                            Name = "North America"
                        },
                        new
                        {
                            GeoNameId = 6255151L,
                            ISO2 = "OC",
                            Name = "Oceania"
                        },
                        new
                        {
                            GeoNameId = 6255150L,
                            ISO2 = "SA",
                            Name = "South America"
                        },
                        new
                        {
                            GeoNameId = 6255152L,
                            ISO2 = "AN",
                            Name = "Antarctica"
                        });
                });

            modelBuilder.Entity("Menchul.GeoNames.org.Models.Country", b =>
                {
                    b.Property<long>("GeoNameId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Area")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Capital")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .IsFixedLength(false);

                    b.Property<string>("ContinentISO2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("CurrencyName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .IsFixedLength(false);

                    b.Property<string>("EquivalentFipsCode")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("Fips")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("ISO2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("ISO3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<int>("ISONumeric")
                        .HasColumnType("int");

                    b.Property<string>("Languages")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .IsFixedLength(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .IsFixedLength(false);

                    b.Property<string>("Neighbours")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .IsFixedLength(false);

                    b.Property<string>("PhoneCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .IsFixedLength(false);

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.Property<string>("PostalCodeFormat")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .IsFixedLength(false);

                    b.Property<string>("PostalCodeRegex")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .IsFixedLength(false);

                    b.Property<string>("TLD")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.HasKey("GeoNameId")
                        .HasName("PK_Countries");

                    b.HasIndex("ContinentISO2");

                    b.ToTable("Countries", "gno");
                });

            modelBuilder.Entity("Menchul.GeoNames.org.Models.FeatureClass", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .IsFixedLength(false);

                    b.HasKey("Code")
                        .HasName("PK_FeatureClasses");

                    b.ToTable("FeatureClasses", "gno");

                    b.HasData(
                        new
                        {
                            Code = "A",
                            Name = "country, state, region,..."
                        },
                        new
                        {
                            Code = "H",
                            Name = "stream, lake,..."
                        },
                        new
                        {
                            Code = "L",
                            Name = "parks,area,..."
                        },
                        new
                        {
                            Code = "P",
                            Name = "city, village,..."
                        },
                        new
                        {
                            Code = "R",
                            Name = "road, railroad"
                        },
                        new
                        {
                            Code = "S",
                            Name = "spot, building, farm"
                        },
                        new
                        {
                            Code = "T",
                            Name = "mountain,hill,rock,..."
                        },
                        new
                        {
                            Code = "U",
                            Name = "undersea"
                        },
                        new
                        {
                            Code = "V",
                            Name = "forest,heath,..."
                        });
                });

            modelBuilder.Entity("Menchul.GeoNames.org.Models.FeatureCode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .IsFixedLength(false);

                    b.Property<string>("FeatureClassCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("FeatureClass")
                        .IsFixedLength();

                    b.HasKey("Code")
                        .HasName("PK_FeatureCodes");

                    b.HasIndex("FeatureClassCode");

                    b.ToTable("FeatureCodes", "gno");
                });

            modelBuilder.Entity("Menchul.GeoNames.org.Models.FeatureCodeName", b =>
                {
                    b.Property<string>("FeatureCodeCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("FeatureCode")
                        .IsFixedLength(false);

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .IsFixedLength(false);

                    b.Property<string>("Description")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .IsFixedLength(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .IsFixedLength(false);

                    b.HasKey("FeatureCodeCode", "Language")
                        .HasName("PK_FeatureCodeNames");

                    b.ToTable("FeatureCodeNames", "gno");
                });

            modelBuilder.Entity("Menchul.GeoNames.org.Models.GeoName", b =>
                {
                    b.Property<long>("GeoNameId")
                        .HasColumnType("bigint");

                    b.Property<string>("ASCIIName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .IsFixedLength(false);

                    b.Property<string>("Admin1Code")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .IsFixedLength(false);

                    b.Property<string>("Admin2Code")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .IsFixedLength(false);

                    b.Property<string>("Admin3Code")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .IsFixedLength(false);

                    b.Property<string>("Admin4Code")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .IsFixedLength(false);

                    b.Property<string>("AlternateNames")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .IsFixedLength(false);

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasColumnName("CountryCode")
                        .IsFixedLength();

                    b.Property<string>("CountryCodesAlternate")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .IsFixedLength(false);

                    b.Property<int>("DEM")
                        .HasColumnType("int");

                    b.Property<int?>("Elevation")
                        .HasColumnType("int");

                    b.Property<string>("FeatureClassCode")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("FeatureClass")
                        .IsFixedLength();

                    b.Property<string>("FeatureCodeCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("FeatureCode")
                        .IsFixedLength(false);

                    b.Property<double>("Latitude")
                        .HasPrecision(8, 5)
                        .HasColumnType("float(8)");

                    b.Property<double>("Longitude")
                        .HasPrecision(8, 5)
                        .HasColumnType("float(8)");

                    b.Property<DateOnly>("ModificationDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)")
                        .IsFixedLength(false);

                    b.Property<long?>("Population")
                        .HasColumnType("bigint");

                    b.Property<string>("TimeZoneName")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .IsFixedLength(false);

                    b.HasKey("GeoNameId")
                        .HasName("PK_GeoNames");

                    b.HasIndex("CountryCode");

                    b.HasIndex("FeatureClassCode");

                    b.HasIndex("FeatureCodeCode");

                    b.HasIndex("TimeZoneName");

                    b.ToTable("GeoNames", "gno");
                });

            modelBuilder.Entity("Menchul.GeoNames.org.Models.ISOLanguage", b =>
                {
                    b.Property<string>("ISO639_3")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("ISO639_1")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("ISO639_2")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ISO639_3")
                        .HasName("PK_ISOLanguages");

                    b.ToTable("ISOLanguages", "gno");
                });

            modelBuilder.Entity("Menchul.GeoNames.org.Models.TimeZone", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .IsFixedLength(false);

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<decimal>("DSTOffset")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("GMTOffset")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("RawOffset")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("Name")
                        .HasName("PK_TimeZones");

                    b.HasIndex("CountryCode");

                    b.ToTable("TimeZones", "gno");
                });

            modelBuilder.Entity("Menchul.GeoNames.org.Models.AlternateNameV2", b =>
                {
                    b.HasOne("Menchul.GeoNames.org.Models.GeoName", "GeoName")
                        .WithMany("AlternateNamesV2")
                        .HasForeignKey("GeoNameIdRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AlternateNameV2_GeoNameId__GeoNames_GeoNameId");

                    b.Navigation("GeoName");
                });

            modelBuilder.Entity("Menchul.GeoNames.org.Models.Country", b =>
                {
                    b.HasOne("Menchul.GeoNames.org.Models.Continent", "Continent")
                        .WithMany("Countries")
                        .HasForeignKey("ContinentISO2")
                        .HasPrincipalKey("ISO2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Continents_ISO2__Countries_ContinentISO2");

                    b.Navigation("Continent");
                });

            modelBuilder.Entity("Menchul.GeoNames.org.Models.FeatureCode", b =>
                {
                    b.HasOne("Menchul.GeoNames.org.Models.FeatureClass", "FeatureClass")
                        .WithMany("Codes")
                        .HasForeignKey("FeatureClassCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FeatureCodes_FeatureClassCode__FeatureClass_Code");

                    b.Navigation("FeatureClass");
                });

            modelBuilder.Entity("Menchul.GeoNames.org.Models.FeatureCodeName", b =>
                {
                    b.HasOne("Menchul.GeoNames.org.Models.FeatureCode", "FeatureCode")
                        .WithMany("Names")
                        .HasForeignKey("FeatureCodeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FeatureCode_Code__FeatureCodeName_FeatureCodeCode");

                    b.Navigation("FeatureCode");
                });

            modelBuilder.Entity("Menchul.GeoNames.org.Models.GeoName", b =>
                {
                    b.HasOne("Menchul.GeoNames.org.Models.Country", "Country")
                        .WithMany("GeoNames")
                        .HasForeignKey("CountryCode")
                        .HasPrincipalKey("ISO2")
                        .HasConstraintName("FK_GeoNames_CountryCode__Countries_ISO2");

                    b.HasOne("Menchul.GeoNames.org.Models.FeatureClass", "FeatureClass")
                        .WithMany("GeoNames")
                        .HasForeignKey("FeatureClassCode")
                        .HasConstraintName("FK_Geonames_FeatureClass__FeatureClass_Code");

                    b.HasOne("Menchul.GeoNames.org.Models.FeatureCode", "FeatureCode")
                        .WithMany("GeoNames")
                        .HasForeignKey("FeatureCodeCode")
                        .HasConstraintName("FK_GeoNames_FeatureCodeCode__FeatureCode_Code");

                    b.HasOne("Menchul.GeoNames.org.Models.TimeZone", "TimeZone")
                        .WithMany("GeoNames")
                        .HasForeignKey("TimeZoneName")
                        .HasConstraintName("FK_GeoNames_TimeZoneName__TimeZones_Name");

                    b.Navigation("Country");

                    b.Navigation("FeatureClass");

                    b.Navigation("FeatureCode");

                    b.Navigation("TimeZone");
                });

            modelBuilder.Entity("Menchul.GeoNames.org.Models.TimeZone", b =>
                {
                    b.HasOne("Menchul.GeoNames.org.Models.Country", "Country")
                        .WithMany("TimeZones")
                        .HasForeignKey("CountryCode")
                        .HasPrincipalKey("ISO2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TimeZones_CountryCode__Countries_ISO2");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Menchul.GeoNames.org.Models.Continent", b =>
                {
                    b.Navigation("Countries");
                });

            modelBuilder.Entity("Menchul.GeoNames.org.Models.Country", b =>
                {
                    b.Navigation("GeoNames");

                    b.Navigation("TimeZones");
                });

            modelBuilder.Entity("Menchul.GeoNames.org.Models.FeatureClass", b =>
                {
                    b.Navigation("Codes");

                    b.Navigation("GeoNames");
                });

            modelBuilder.Entity("Menchul.GeoNames.org.Models.FeatureCode", b =>
                {
                    b.Navigation("GeoNames");

                    b.Navigation("Names");
                });

            modelBuilder.Entity("Menchul.GeoNames.org.Models.GeoName", b =>
                {
                    b.Navigation("AlternateNamesV2");
                });

            modelBuilder.Entity("Menchul.GeoNames.org.Models.TimeZone", b =>
                {
                    b.Navigation("GeoNames");
                });
#pragma warning restore 612, 618
        }
    }
}
