<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\props\Menchul.GeoNames.org.pckg.props" />

    <PropertyGroup>
        <Title>DB EF library for Geonames.org</Title>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <Import Project="..\targets\Microsoft.EntityFrameworkCore.Design.targets" />
    <Import Project="..\targets\Microsoft.EntityFrameworkCore.Relational.targets" />

    <ItemGroup>
        <None Include="..\..\README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

</Project>