<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\props\Menchul.GeoNames.org.pckg.props" />

    <Import Project="..\targets\Microsoft.EntityFrameworkCore.Design.targets" />
    <Import Project="..\targets\Microsoft.EntityFrameworkCore.Sqlite.Core.targets" />
    <Import Project="..\targets\SQLitePCLRaw.bundle_e_sqlite3.targets" />

    <ItemGroup>
        <ProjectReference Include="..\Menchul.GeoNames.org\Menchul.GeoNames.org.csproj" />
    </ItemGroup>

    <Import Project="..\targets\Microsoft.Extensions.Configuration.CommandLine.targets" />

</Project>